export const QUOTES: string[] = [
    "One book, one pen, one child and one teacher can change the world. - Malala Yousafzai",
    "In learning you will teach, and in teaching you will learn. - Phil Collins",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world. - Anne Frank",
    "We never know which lives we influence, or when or why. - Stephen King",
    "We can't help everyone, but everyone can help someone. - Ronald Reagan",
    "Students don't care how much you know until they know how much you care. - John C. Maxwell",
    "The world is changed by your example not by your opinion. - Paulo Coelho",
    "A well-educated mind will always have more questions than answers. - Helen Keller",
    "Our fingerprints don't fade from the lives we touch. - Judy Blume",
    "Educating the mind without educating the heart is no education at all. - Aristotle",
    "Nine-tenths of education is encouragement. - Anatole France",
    "It is the supreme art of the teacher to awaken joy in creative expression and knowledge. - Albert Einstein",
    "Teaching is the highest form of understanding. - Aristotle",
    "I am not a teacher, but an awakener. - Robert Frost",
    "Those who know, do. Those that understand, teach. - Aristotle",
    "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires. - William Arthur Ward",
    "Education is not the filling of a pail, but the lighting of a fire. - William Butler Yeats",
    "A good teacher is one who makes himself progressively unnecessary. - Thomas Carruthers",
    "Teaching might even be the greatest of the arts since the medium is the human mind and spirit. - John Steinbeck",
    "The great teacher is not the man who supplies the most facts, but the one in whose presence we become different people - Ralph Waldo Emerson",
    "Give me a fish and I eat for a day. Teach me to fish and I eat for a lifetime. - Chinese Proverb",
    "Better than a thousand days of diligent study is one day with a great teacher. - Japanese Proverb",
    "He who opens a school door closes a prison. - Victor Hugo"
];